on:
  push:
    branches:
      - master

jobs:
  e2e-tests:
    runs-on: ubuntu-latest # or macos-latest, windows-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1

      - uses: microsoft/playwright-github-action@v1

      - name: Install dependencies
        run: npm install

      - name: Run ESLint on all files and fix potentially fixable errors/warnings
        run: npx eslint . --fix

      - name: Install playwright and run tests
        run: npx playwright install && npx playwright test